### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [icodeforlove/Colors#5]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by icodeforlove** [comment]
Would love to see a pull request :) 

Kinda temporarily out of the iOS/OSX dev ring.

Added you as a collaborator to inspire motivation :P

**Comment by lfarah** [comment]
Thanks @icodeforlove. I'll see what I can do! 😉
